CIS4339-18068-Project-Justin-Thomas-v3/config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :vehicles

  get 'home/index'

  resources :customers

  root 'home#index'

end

CIS4339-18068-Project-Justin-Thomas-v3/app/controllers/salespeople_controller.rb
class SalespeopleController < ApplicationController
  before_action :set_salesperson, only: [:show, :edit, :update, :destroy]

  # GET /salespeople
  # GET /salespeople.json
  def index
    @salespeople = Salesperson.all
  end

  # GET /salespeople/1
  # GET /salespeople/1.json
  def show
  end

  # GET /salespeople/new
  def new
    @salesperson = Salesperson.new
  end

  # GET /salespeople/1/edit
  def edit
  end

  # POST /salespeople
  # POST /salespeople.json
  def create
    @salesperson = Salesperson.new(salesperson_params)

    respond_to do |format|
      if @salesperson.save
        format.html { redirect_to @salesperson, notice: 'Salesperson was successfully created.' }
        format.json { render :show, status: :created, location: @salesperson }
      else
        format.html { render :new }
        format.json { render json: @salesperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salespeople/1
  # PATCH/PUT /salespeople/1.json
  def update
    respond_to do |format|
      if @salesperson.update(salesperson_params)
        format.html { redirect_to @salesperson, notice: 'Salesperson was successfully updated.' }
        format.json { render :show, status: :ok, location: @salesperson }
      else
        format.html { render :edit }
        format.json { render json: @salesperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salespeople/1
  # DELETE /salespeople/1.json
  def destroy
    @salesperson.destroy
    respond_to do |format|
      format.html { redirect_to salespeople_url, notice: 'Salesperson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesperson
      @salesperson = Salesperson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesperson_params
      params.require(:salesperson).permit(:sp_fname, :sp_lname)
    end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/helpers/salespeople_helper.rb
module SalespeopleHelper
end

CIS4339-18068-Project-Justin-Thomas-v3/app/views/salespeople/_form.html.erb
<%= form_for(@salesperson) do |f| %>
  <% if @salesperson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salesperson.errors.count, "error") %> prohibited this salesperson from being saved:</h2>

      <ul>
      <% @salesperson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sp_fname, "First Name" %><br>
    <%= f.text_field :sp_fname %>
  </div>
  <div class="field">
    <%= f.label :sp_lname, "Last Name" %><br>
    <%= f.text_field :sp_lname %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/salespeople/edit.html.erb
<h1>Edit Salesperson</h1>

<%= render 'form' %>

<%= link_to 'Show', @salesperson %> |
<%= link_to 'Back', salespeople_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/salespeople/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Salespeople</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Total Sales</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salespeople.each do |salesperson| %>
      <tr>
        <td><%= salesperson.spfullname %></td>
        <td><%= salesperson.quotes.where(:is_sold => true).size %></td>
        <td><%= link_to 'Show', salesperson %></td>
        <td><%= link_to 'Edit', edit_salesperson_path(salesperson) %></td>
        <td><%= link_to 'Delete', salesperson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Salesperson', new_salesperson_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/salespeople/new.html.erb
<h1>Create Salesperson</h1>

<%= render 'form' %>

<%= link_to 'Back', salespeople_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/salespeople/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @salesperson.sp_fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @salesperson.sp_lname %>
</p>

<p>
  <strong>Total Sales:</strong>
  <%= @salesperson.quotes.where(:is_sold => true).size %>
</p>

<%= link_to 'Edit', edit_salesperson_path(@salesperson) %> |
<%= link_to 'Back', salespeople_path %>