CIS4339-18068-Project-Justin-Thomas-v3/config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :vehicles

  get 'home/index'

  resources :customers

  root 'home#index'

end

CIS4339-18068-Project-Justin-Thomas-v3/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :customer
  belongs_to :vehicle
  belongs_to :salesperson
  validates_inclusion_of :is_sold, :in => [true, false]


  def self.pay_years
    [3, 4, 5]
  end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
    @vehicle = Vehicle.all
    @salesperson = Salesperson.all
    @customer = Customer.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new

  end

  # GET /quotes/1/edit
  def edit

  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :vehicle_id, :salesperson_id, :sale_price, :interest_rate, :payment_years, :is_sold)
    end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/helpers/quotes_helper.rb
module QuotesHelper
end

CIS4339-18068-Project-Justin-Thomas-v3/app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :custfullname %>
  </div>
  <div class="field">
    <%= f.label :vehicle %><br>
    <%= f.collection_select :vehicle_id, Vehicle.all, :id, :vin %>
  </div>
  <div class="field">
    <%= f.label :salesperson %><br>
    <%= f.collection_select :salesperson_id, Salesperson.all, :id, :spfullname %>
  </div>
  <div class="field">
    <%= f.label :sale_price %><br>
    <%= f.text_field :sale_price %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :payment_years %><br>
    <%= f.select :payment_years, Quote.pay_years %>
  </div>
  <div class="field">
    <%= f.label :is_sold, "Sold?" %><br>
    <%= f.radio_button :is_sold, true %><label>Yes</label><br>
    <%= f.radio_button :is_sold, false %><label>No</label>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/quotes/edit.html.erb
<h1>Edit Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Vehicle</th>
      <th>Salesperson</th>
      <th>Sale price</th>
      <th>Interest rate</th>
      <th>Payment years</th>
      <th>Sold?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer.custfullname %></td>
        <td><%= quote.vehicle.vin %></td>
        <td><%= quote.salesperson.spfullname %></td>
        <td><%= number_to_currency(quote.sale_price) %></td>
        <td><%= number_to_percentage(quote.interest_rate) %></td>
        <td><%= quote.payment_years %></td>
        <td><%= yesno(quote.is_sold) %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Quote', new_quote_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/quotes/new.html.erb
<h1>Create Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.custfullname %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @quote.vehicle.vin %>
</p>

<p>
  <strong>Salesperson:</strong>
  <%= @quote.salesperson.spfullname %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @quote.sale_price %>
</p>

<p>
  <strong>Interest rate:</strong>
  <%= @quote.interest_rate %>
</p>

<p>
  <strong>Payment years:</strong>
  <%= @quote.payment_years %>
</p>

<p>
  <strong>Sold?</strong>
  <%= yesno(@quote.is_sold) %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>