CIS4339-18068-Project-Justin-Thomas-v3/config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :vehicles

  get 'home/index'

  resources :customers

  root 'home#index'

end

CIS4339-18068-Project-Justin-Thomas-v3/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  accepts_nested_attributes_for :quotes

  def self.search(query)
    where("cust_lname like ? or cust_fname like ?", "%#{query}%", "%#{query}%")
  end

  def custfullname
    "#{cust_fname} #{cust_lname}"
  end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    if params[:search]
      @customers = Customer.search(params[:search]).order("created_at DESC")
    else
      @customers = Customer.all.order('created_at DESC')
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:cust_fname, :cust_lname)
    end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/helpers/customers_helper.rb
module CustomersHelper
end

CIS4339-18068-Project-Justin-Thomas-v3/app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cust_fname, "First Name" %><br>
    <%= f.text_field :cust_fname %>
  </div>
  <div class="field">
    <%= f.label :cust_lname, "Last Name" %><br>
    <%= f.text_field :cust_lname %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<%= form_tag(customers_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.custfullname %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Delete', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create Customer', new_customer_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/customers/new.html.erb
<h1>Create Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @customer.cust_fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @customer.cust_lname %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>