CIS4339-18068-Project-Justin-Thomas-v3/config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :salespeople

  resources :vehicles

  get 'home/index'

  resources :customers

  root 'home#index'

end

CIS4339-18068-Project-Justin-Thomas-v3/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  has_many :quotes
  accepts_nested_attributes_for :quotes

  def self.search(query)
    where("model like ? or color like ? or vin like ?", "%#{query}%", "%#{query}%", "%#{query}%")
  end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    if params[:search]
      @vehicles = Vehicle.search(params[:search]).order("created_at DESC")
    else
      @vehicles = Vehicle.all.order('created_at DESC')
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:model, :color, :vin, :wholesale_price)
    end
end

CIS4339-18068-Project-Justin-Thomas-v3/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

CIS4339-18068-Project-Justin-Thomas-v3/app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.number_field :vin %>
  </div>
  <div class="field">
    <%= f.label :wholesale_price, "Wholesale Price" %><br>
    <%= f.text_field :wholesale_price, :value=>number_to_currency(f.object.wholesale_price) %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/vehicles/edit.html.erb
<h1>Edit Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<%= form_tag(vehicles_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search]%>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Wholesale price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.model %></td>
        <td><%= vehicle.color %></td>
        <td><%= vehicle.vin %></td>
        <td><%= number_to_currency(vehicle.wholesale_price) %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Delete', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add Vehicle', new_vehicle_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/vehicles/new.html.erb
<h1>Add Vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

CIS4339-18068-Project-Justin-Thomas-v3/app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @vehicle.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @vehicle.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @vehicle.vin %>
</p>

<p>
  <strong>Wholesale price:</strong>
  <%= number_to_currency(@vehicle.wholesale_price) %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>